### ISSUE TITLE
Undefined error

### ISSUE THREAD

**Issue by xongkoro3** [lupas/nuxt2-firestore#1]
Whenever I use 'this.$fireStorage' or 'app.$fireStorage' in plugins, it's throwing me an error of undefined: 'this'/'app' is undefined.

**Comment by lupas** [comment]
@xongkoro3 
Can you please open up the issue in the [nuxt-fire](https://github.com/lupas/nuxt-fire) repository and add code bits of your **plugin** as well your **nuxt.config.js** file to the issue?
Thanks
